### ISSUE TITLE
cannot decode multi-level nested message structures

### ISSUE THREAD

**Issue by itbencn** [sandermvanvliet/ProtobufDecoder#33]
Hi
First of all, this is a great project
I found that the ProtobufDecoder cannot decode multi-level nested message structures, and can only decode to the second layer at most.

**Comment by sandermvanvliet** [comment]
Do you have an example payload that demonstrates the problem?

I’ve tested with some messages that nest different message types (IIRC some 5 levels deep) but Protobuf allows you to do some “interesting” things so I suspect the message you’re decoding has a form that I haven’t encountered and therefore ProtobufDecoder has no idea how to deal with it

**Comment by itbencn** [comment]
proto struct
```
    [ProtoContract]
    public class ObjClass1
    {
        [ProtoMember(1)]
        public uint IntValue { get; set; }
        [ProtoMember(2)]
        public byte[] ByteValue { get; set; }
        [ProtoMember(3)]
        public string StringValue { get; set; }
        [ProtoMember(4)]
        public ObjClass2 ObjValue { get; set; }
    }

    [ProtoContract]
    public class ObjClass2
    {
        [ProtoMember(1)]
        public uint IntValue { get; set; }
        [ProtoMember(2)]
        public byte[] ByteValue { get; set; }
        [ProtoMember(3)]
        public string StringValue { get; set; }
        [ProtoMember(4)]
        public ObjClass3 ObjValue { get; set; }
    }

    [ProtoContract]
    public class ObjClass3
    {
        [ProtoMember(1)]
        public uint IntValue { get; set; }
        [ProtoMember(2)]
        public byte[] ByteValue { get; set; }
        [ProtoMember(3)]
        public string StringValue { get; set; }
    }
```
test
```
            ObjClass1 objClass1 = new ObjClass1()
            {
                IntValue = 1,
                ByteValue = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 },
                StringValue = "ObjClass1",
                ObjValue = new ObjClass2
                {
                    IntValue = 2,
                    ByteValue = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 },
                    StringValue = "ObjClass2",
                    ObjValue = new ObjClass3
                    {
                        IntValue = 3,
                        ByteValue = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 },
                        StringValue = "ObjClass3"
                    }
                }
            };
//output:080112090102030405060708091A094F626A436C617373312232080212090102030405060708091A094F626A436C617373322218080312090102030405060708091A094F626A436C61737333
```

**Comment by sandermvanvliet** [comment]
Thanks, I’ll have a look in the next few days

**Comment by sandermvanvliet** [comment]
With this proto file:
```proto
syntax="proto3";

message Message1
{
    int32 intValue = 1;
    bytes byteValue = 2;
    string stringValue = 3;
    Message2 objValue = 4;
}

message Message2
{
    int32 intValue = 1;
    bytes byteValue = 2;
    string stringValue = 3;
    Message3 objValue = 4;
}

message Message3
{
    int32 intValue = 1;
    bytes byteValue = 2;
    string stringValue = 3;
}
```

and constructing a sample of that like so:

```csharp
var message = new Message1
{
    IntValue = 1,
    StringValue = "one",
    ByteValue = ByteString.CopyFrom(0x1, 0x1),
    ObjValue = new Message2
    {
        IntValue = 2,
        StringValue = "two",
        ByteValue = ByteString.CopyFrom(0x2, 0x2),
        ObjValue = new Message3
        {
            IntValue = 3,
            StringValue = "three",
            ByteValue = ByteString.CopyFrom(0x3, 0x3),
        }
    }
};
```

I've managed to get that to decode:

https://user-images.githubusercontent.com/2393265/192099337-c33884ac-fd41-4caf-94a4-1d82c379b24d.mp4

This works on version 0.6.0 and in the upcoming 0.7.0.

Would it be possible for you to make a screen recording to show what doesn't work?

**Comment by itbencn** [comment]
Wow, that's great,
I was careless and ignored the right-click menu "Decode tag" in the tree box node
That is to say, the tool resolves to two levels by default, and deeper nodes need to manually "Decode tag"
`It is recommended to add relevant prompts.`

This is different from the temporary analysis tool I wrote before, so I have some qualitative thinking,
My own tool automatically parses all nodes through recursive loops, but there is a problem. Occasionally, strings are parsed into multiple nodes, which is why I gave up my tool.

**Comment by sandermvanvliet** [comment]
I can add some more smarts to "turtle all the way down", let me see if I can make that work.

The string stuff is already quite heavily hinted in ProtobufDecoder and it tries to be smart about it.

**Comment by itbencn** [comment]
<img width="794" alt="Snipaste_2022-09-24" src="https://user-images.githubusercontent.com/42700064/192101865-c506c6bf-9d15-4ba5-a81d-a1f16ddfaef7.png">

**Comment by itbencn** [comment]
Do you have tg or other social contact information
Whether the "ThriftDecoder" tool can be customized to decode the Thrift binary data will not affect your continued open source. I will pay a certain fee to support open source.

**Comment by sandermvanvliet** [comment]
I've created a group on Signal: https://signal.group/#CjQKIHaJW5q1Nx9_v5c9PMfPdC0c-htYlr1oTiw3sGXcf2gYEhDV7Yn_S4Uk_D5xHDyE2o2y where you can reach me :+1:
